### ISSUE TITLE
Current license / apply MIT license?

### ISSUE THREAD

**Issue by hartwork** [davvidbaker/fonts#1]
Hi!

I didn't find any notes on license in here. If you have picked a free software license already, please make it more visible. Else, please apply [one of the popular free software licenses](https://opensource.org/licenses), e.g. the MIT license.

Many thanks!

**Comment by davvidbaker** [comment]
Added MIT License. Thanks for the feedback!

**Comment by hartwork** [comment]
Excellent, thank you!
